# Generated by Django 5.2.6 on 2025-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['profile', 'start_date'], name='Tour_subscr_profile_debe8d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='Tour_subscr_end_dat_49b2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['transaction_id'], name='Tour_subscr_transac_9d40fb_idx'),
        ),
    ]
