# Generated by Django 5.2.6 on 2025-09-22 03:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='Tour.booking')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='activities', to='Tour.traveler'),
        ),
        migrations.AddField(
            model_name='diningexpense',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='dining_expenses', to='Tour.traveler'),
        ),
        migrations.AddField(
            model_name='stay',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='stays', to='Tour.traveler'),
        ),
        migrations.AddField(
            model_name='travelleg',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='travel_legs', to='Tour.traveler'),
        ),
    ]
